name: stocksapp
description: Инвест-Аналитик Pro - профессиональное приложение для анализа акций
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.0
  injectable: ^2.1.0
  
  # Navigation (ЗАМЕНА AutoRoute на GoRouter)
  go_router: ^12.1.3  # Новый пакет для маршрутизации
  
  # Network
  dio: ^4.0.6
  retrofit: ^3.3.1
  logger: ^1.4.0
  
  # Local Storage & Security
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.1
  
  # Localization
  easy_localization: ^3.0.1
  
  # UI & Utilities
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  pull_to_refresh: ^2.0.0
  syncfusion_flutter_charts: ^31.1.19
  fl_chart: ^0.61.0
  window_manager: ^0.3.3
  
  # Payments
  in_app_purchase: ^3.1.9
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  firebase_messaging: ^14.7.0
  
  # Biometric Auth
  local_auth: ^2.1.2
  
  # Platform-specific
  url_launcher: ^6.1.10
  package_info_plus: ^4.1.0
  device_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  analyzer: ^5.13.0
  retrofit_generator: ^4.1.0+1
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700